### ISSUE TITLE
Error: Invalid or corrupt jarfile pdfunlock on Mac

### ISSUE THREAD

**Issue by VirenMohindra** [kilburn/pdfunlock#1]
MacBook Pro (Retina, 15-inch, Mid 2015)
2.2 GHz Intel Core i7 Processor
16 GB 1600 MHz DDR3 RAM
Intel Iris Pro 1536 MB Graphics Card

Installed `ant` with homebrew and packaging succeeded, but I got the above error.

**Comment by kilburn** [comment]
I'm pretty sure this is some problem with your java/jdk version. Please update java and try again...
