### ISSUE TITLE
Can't unlock the pdf file

### ISSUE THREAD

**Issue by birdhur** [kilburn/pdfunlock#2]
Hello  Kilburn,

   I have tried used this project.  And i used one pdf file with password to test, but the unlock operation failed. The error message is bad user password.  
    If you find this error when using it to unlock the pdf files?

  Thanks for your work!

**Comment by kilburn** [comment]
This project only works with non-encrypted (password-protected) files. It is there to remove the print/copy protection, not to remove password protections (which are an entirely different matter).
